// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuFnvjVbi0SRBxbq6XwfuSwgO5WIYVlHg',
    appId: '1:663414934306:android:0f3c143d45a83e80a1337b',
    messagingSenderId: '663414934306',
    projectId: 'compact-haiku-424413-j3',
    storageBucket: 'compact-haiku-424413-j3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoaBtz9d05vuDif2dHJ0GMoGqXV0C7UTM',
    appId: '1:663414934306:ios:11f10f8f024c2fa5a1337b',
    messagingSenderId: '663414934306',
    projectId: 'compact-haiku-424413-j3',
    storageBucket: 'compact-haiku-424413-j3.firebasestorage.app',
    iosBundleId: 'com.example.dropMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ2lyLAR3IrtXfBgbK54Cmrvs4fc4jNnU',
    appId: '1:663414934306:web:88bc7dc393474bbda1337b',
    messagingSenderId: '663414934306',
    projectId: 'compact-haiku-424413-j3',
    authDomain: 'compact-haiku-424413-j3.firebaseapp.com',
    storageBucket: 'compact-haiku-424413-j3.firebasestorage.app',
  );

}