default_platform(:ios)

platform :ios do
  desc "Deploy to Firebase App Distribution"
  lane :deploy do
    build_ios_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "ad-hoc"
    )
    
    firebase_app_distribution(
      app: ENV["FIREBASE_IOS_APP_ID"],
      groups: "testers",
      release_notes: "Automated release via Fastlane"
    )
  end
end