default_platform(:android)

platform :android do
  desc "Deploy to Firebase App Distribution"
  lane :deploy do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    
    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"],
      groups: "testers",
      release_notes: "Automated release via Fastlane",
      apk_path: "build/app/outputs/flutter-apk/app-release.apk"
    )
  end
end